# Manually print each "knot" one by one.
print("By knot of 1, The spell's begun.")
print("By knot of 2, It comes true.")
print("By knot of 3, So mote it be.")
print("By knot of 4, This power I store.")
print("By knot of 5, The spell's alive.")
print("By knot of 6, This spell I fix.")
print("By knot of 7, Events I'll leaven.")
print("By knot of 8, It will be fate.")
print("By knot of 9, What's done is mine.")
